name: uptime_kuma
services:
  uptime_kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:1
    ports:
      - "3209:3001"
    volumes:
      - uptime-kuma:/app/data
      - ./certs/uptime_kuma_key.pem:/app/data/docker-tls/uptime-kuma.key
      - ./certs/uptime_kuma_fullchain.pem:/app/data/docker-tls/uptime-kuma.crt 
      - ./certs/ca.cert.pem:/app/data/docker-tls/ca.cert.pem
        #- /var/run/docker.sock:/var/run/docker.sock #  sharing docker.sock with Uptime Kuma container to monitor docker container statues. 
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      UPTIME_KUMA_SSL_KEY: /app/data/docker-tls/uptime-kuma.key
      UPTIME_KUMA_SSL_CERT: /app/data/docker-tls/uptime-kuma.crt 
      NODE_EXTRA_CA_CERTS: /app/data/docker-tls/ca.cert.pem
    cpus: "0.50"
    domainname: kuma-tq.thetinkerer.dev
    healthcheck:
      test: ["CMD-SHELL", "curl -fk https://localhost:3001 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 30s
      start_interval: 5s
    hostname: kuma-tq
    mem_limit: "1536M"
    pull_policy: "missing"
    stop_grace_period: 1m

volumes:
  uptime-kuma:
